-
  branches:
      only:
        - master
        - /release\/.*/
  version: 1.0.{build}
  image: Visual Studio 2017
  before_build:
  - cmd: dotnet --info
  environment:
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: Kse62H9lWHIwjsqpi2ih1efUnHc5R6VfIzu1Nfr/CXcJSKPkH8EGElCIxvP43/Oh
  build_script:
  - ps: .\build.ps1
  test: off
  cache:
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
  on_failure:
  - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
-
  branches:
      only:
        - develop
  version: 1.0.{build}
  image: Visual Studio 2017
  before_build:
  - cmd: dotnet --info
  environment:
    NUGET_SOURCE: https://www.myget.org/F/martijn00/api/v2/package
    NUGET_APIKEY:
      secure: 0PNC9eZWAinI1KkE9usbhPAwF1wudL5GJi6lJn9Ylb67M7SE17LIXBoMHuRKJaLE
  build_script:
  - ps: .\build.ps1
  test: off
  cache:
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache
  on_failure:
  - ps: Get-ChildItem *.binlog -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }